name = "FundamentalsNumericalComputation"
uuid = "e48b7b93-d2a8-4750-aba7-f743ccd5256c"
authors = ["Toby Driscoll <driscoll@udel.edu>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
